# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/compal/gitrep/vsAliens

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/compal/gitrep/vsAliens

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/compal/gitrep/vsAliens/CMakeFiles /home/compal/gitrep/vsAliens/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/compal/gitrep/vsAliens/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vsAliens

# Build rule for target.
vsAliens: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsAliens
.PHONY : vsAliens

# fast build rule for target.
vsAliens/fast:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/build
.PHONY : vsAliens/fast

src/Bonus.o: src/Bonus.cpp.o

.PHONY : src/Bonus.o

# target to build an object file
src/Bonus.cpp.o:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Bonus.cpp.o
.PHONY : src/Bonus.cpp.o

src/Bonus.i: src/Bonus.cpp.i

.PHONY : src/Bonus.i

# target to preprocess a source file
src/Bonus.cpp.i:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Bonus.cpp.i
.PHONY : src/Bonus.cpp.i

src/Bonus.s: src/Bonus.cpp.s

.PHONY : src/Bonus.s

# target to generate assembly for a file
src/Bonus.cpp.s:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Bonus.cpp.s
.PHONY : src/Bonus.cpp.s

src/Bullet.o: src/Bullet.cpp.o

.PHONY : src/Bullet.o

# target to build an object file
src/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Bullet.cpp.o
.PHONY : src/Bullet.cpp.o

src/Bullet.i: src/Bullet.cpp.i

.PHONY : src/Bullet.i

# target to preprocess a source file
src/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Bullet.cpp.i
.PHONY : src/Bullet.cpp.i

src/Bullet.s: src/Bullet.cpp.s

.PHONY : src/Bullet.s

# target to generate assembly for a file
src/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Bullet.cpp.s
.PHONY : src/Bullet.cpp.s

src/Character.o: src/Character.cpp.o

.PHONY : src/Character.o

# target to build an object file
src/Character.cpp.o:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Character.cpp.o
.PHONY : src/Character.cpp.o

src/Character.i: src/Character.cpp.i

.PHONY : src/Character.i

# target to preprocess a source file
src/Character.cpp.i:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Character.cpp.i
.PHONY : src/Character.cpp.i

src/Character.s: src/Character.cpp.s

.PHONY : src/Character.s

# target to generate assembly for a file
src/Character.cpp.s:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Character.cpp.s
.PHONY : src/Character.cpp.s

src/Enemy.o: src/Enemy.cpp.o

.PHONY : src/Enemy.o

# target to build an object file
src/Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Enemy.cpp.o
.PHONY : src/Enemy.cpp.o

src/Enemy.i: src/Enemy.cpp.i

.PHONY : src/Enemy.i

# target to preprocess a source file
src/Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Enemy.cpp.i
.PHONY : src/Enemy.cpp.i

src/Enemy.s: src/Enemy.cpp.s

.PHONY : src/Enemy.s

# target to generate assembly for a file
src/Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Enemy.cpp.s
.PHONY : src/Enemy.cpp.s

src/Hud.o: src/Hud.cpp.o

.PHONY : src/Hud.o

# target to build an object file
src/Hud.cpp.o:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Hud.cpp.o
.PHONY : src/Hud.cpp.o

src/Hud.i: src/Hud.cpp.i

.PHONY : src/Hud.i

# target to preprocess a source file
src/Hud.cpp.i:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Hud.cpp.i
.PHONY : src/Hud.cpp.i

src/Hud.s: src/Hud.cpp.s

.PHONY : src/Hud.s

# target to generate assembly for a file
src/Hud.cpp.s:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Hud.cpp.s
.PHONY : src/Hud.cpp.s

src/Ship.o: src/Ship.cpp.o

.PHONY : src/Ship.o

# target to build an object file
src/Ship.cpp.o:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Ship.cpp.o
.PHONY : src/Ship.cpp.o

src/Ship.i: src/Ship.cpp.i

.PHONY : src/Ship.i

# target to preprocess a source file
src/Ship.cpp.i:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Ship.cpp.i
.PHONY : src/Ship.cpp.i

src/Ship.s: src/Ship.cpp.s

.PHONY : src/Ship.s

# target to generate assembly for a file
src/Ship.cpp.s:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/Ship.cpp.s
.PHONY : src/Ship.cpp.s

src/functional.o: src/functional.cpp.o

.PHONY : src/functional.o

# target to build an object file
src/functional.cpp.o:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/functional.cpp.o
.PHONY : src/functional.cpp.o

src/functional.i: src/functional.cpp.i

.PHONY : src/functional.i

# target to preprocess a source file
src/functional.cpp.i:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/functional.cpp.i
.PHONY : src/functional.cpp.i

src/functional.s: src/functional.cpp.s

.PHONY : src/functional.s

# target to generate assembly for a file
src/functional.cpp.s:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/functional.cpp.s
.PHONY : src/functional.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/settings.o: src/settings.cpp.o

.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i

.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s

.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) -f CMakeFiles/vsAliens.dir/build.make CMakeFiles/vsAliens.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vsAliens"
	@echo "... src/Bonus.o"
	@echo "... src/Bonus.i"
	@echo "... src/Bonus.s"
	@echo "... src/Bullet.o"
	@echo "... src/Bullet.i"
	@echo "... src/Bullet.s"
	@echo "... src/Character.o"
	@echo "... src/Character.i"
	@echo "... src/Character.s"
	@echo "... src/Enemy.o"
	@echo "... src/Enemy.i"
	@echo "... src/Enemy.s"
	@echo "... src/Hud.o"
	@echo "... src/Hud.i"
	@echo "... src/Hud.s"
	@echo "... src/Ship.o"
	@echo "... src/Ship.i"
	@echo "... src/Ship.s"
	@echo "... src/functional.o"
	@echo "... src/functional.i"
	@echo "... src/functional.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

